stages:
  get_data:
    cmd: 
      - mkdir data\raw
      - tar -xvzf data\train_val.zip -C data\raw
    deps:
      - data\train_val.zip
    outs:
      - data\raw 
  
  preprocessing:
    cmd: python src\preprocess.py
    deps: 
      - data\raw
      - src\preprocess.py
    outs:
      - data\clean
    params:
      - preprocessing

  train:
    cmd: python src\train.py
    deps: 
      - src\core
      - data\clean
      - src\train.py
    outs:
      - weights
    params:
      - transform
      - dataset
      - model
    metrics:
      - dvclive\metrics.json
    plots:
      - dvclive\plots
